/**
 * Best-effort emoji lookup for an ingredient name. Used as a fallback when the
 * AI omits an emoji and inside the mock AI provider.
 */

const EMOJI: Record<string, string> = {
  egg: "🥚",
  eggs: "🥚",
  carrot: "🥕",
  ramen: "🍜",
  noodle: "🍜",
  noodles: "🍜",
  pasta: "🍝",
  spaghetti: "🍝",
  garlic: "🧄",
  butter: "🧈",
  kimchi: "🥬",
  "green onion": "🧅",
  scallion: "🧅",
  "spring onion": "🧅",
  onion: "🧅",
  tofu: "🧊",
  pork: "🥩",
  beef: "🥩",
  steak: "🥩",
  meat: "🥩",
  chicken: "🍗",
  fish: "🐟",
  salmon: "🐟",
  tuna: "🐟",
  shrimp: "🦐",
  prawn: "🦐",
  squid: "🦑",
  octopus: "🐙",
  crab: "🦀",
  bacon: "🥓",
  ham: "🍖",
  sausage: "🌭",
  rice: "🍚",
  bread: "🍞",
  baguette: "🥖",
  flour: "🌾",
  cereal: "🥣",
  milk: "🥛",
  cheese: "🧀",
  yogurt: "🥛",
  cream: "🥛",
  tomato: "🍅",
  potato: "🥔",
  cucumber: "🥒",
  lettuce: "🥬",
  cabbage: "🥬",
  spinach: "🥬",
  broccoli: "🥦",
  mushroom: "🍄",
  pepper: "🫑",
  "bell pepper": "🫑",
  chili: "🌶️",
  "chili flake": "🌶️",
  gochugaru: "🌶️",
  gochujang: "🌶️",
  corn: "🌽",
  bean: "🫘",
  beans: "🫘",
  pea: "🫛",
  peas: "🫛",
  eggplant: "🍆",
  pumpkin: "🎃",
  ginger: "🫚",
  sesame: "🌰",
  apple: "🍎",
  banana: "🍌",
  orange: "🍊",
  lemon: "🍋",
  lime: "🍋",
  strawberry: "🍓",
  grape: "🍇",
  grapes: "🍇",
  watermelon: "🍉",
  peach: "🍑",
  pear: "🍐",
  pineapple: "🍍",
  mango: "🥭",
  avocado: "🥑",
  coconut: "🥥",
  kiwi: "🥝",
  blueberry: "🫐",
  honey: "🍯",
  jam: "🍯",
  sugar: "🧂",
  salt: "🧂",
  oil: "🫒",
  "olive oil": "🫒",
  "soy sauce": "🥢",
  sauce: "🥫",
  ketchup: "🍅",
  mayo: "🥚",
  mayonnaise: "🥚",
  water: "💧",
  juice: "🧃",
  soda: "🥤",
  coffee: "☕",
  tea: "🍵",
  beer: "🍺",
  wine: "🍷",
  chocolate: "🍫",
  candy: "🍬",
  cookie: "🍪",
  cake: "🍰",
  "ice cream": "🍦",
  salad: "🥗",
  soup: "🍲",
  dumpling: "🥟",
  pizza: "🍕",
  burger: "🍔",
};

const SORTED_KEYS = Object.keys(EMOJI).sort((a, b) => b.length - a.length);

export function emojiFor(name: string): string {
  const n = name.toLowerCase().trim();
  if (EMOJI[n]) return EMOJI[n];
  for (const key of SORTED_KEYS) {
    if (n.includes(key)) return EMOJI[key];
  }
  return "🥘";
}
