"""Recipe + recommendation contracts.

`RecipeCandidate` is the vendor-neutral recipe a `RecipeSource` returns,
whether curated from the seed DB or generated by an LLM. The recommendation
service scores candidates against live inventory to produce `RecipeMatch`.
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class RecipeCandidateIngredient(BaseModel):
    name: str
    quantity: float | None = None
    unit: str | None = None
    is_essential: bool = True


class RecipeCandidate(BaseModel):
    """A recipe proposed by a RecipeSource (seed DB or LLM), pre-scoring."""

    name: str
    cuisine: str | None = "한식"
    instructions: str | None = None
    image_url: str | None = None
    cook_minutes: int | None = None
    origin: str = "seed"  # seed | llm
    # Present for seed recipes so "made it" can deduct deterministically.
    recipe_id: int | None = None
    ingredients: list[RecipeCandidateIngredient] = Field(default_factory=list)


class RecipeIngredientOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    ingredient_id: int | None = None
    name: str
    quantity: float | None = None
    unit: str | None = None
    is_essential: bool = True


class RecipeOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int | None = None
    name: str
    cuisine: str | None = None
    instructions: str | None = None
    image_url: str | None = None
    cook_minutes: int | None = None
    origin: str = "seed"
    ingredients: list[RecipeIngredientOut] = Field(default_factory=list)


class RecipeMatch(BaseModel):
    """A scored recommendation: recipe + how well it fits current stock."""

    recipe: RecipeOut
    score: float
    completeness: float = Field(..., description="have / essential ratio (0..1)")
    have: list[str] = Field(default_factory=list)
    missing: list[str] = Field(default_factory=list)
    uses_urgent: list[str] = Field(
        default_factory=list, description="Urgent (soon-expiring) ingredients used"
    )


class ShoppingListItem(BaseModel):
    name: str
    needed_by_recipes: list[str] = Field(default_factory=list)


class RecommendationResponse(BaseModel):
    matches: list[RecipeMatch] = Field(default_factory=list)
    shopping_list: list[ShoppingListItem] = Field(default_factory=list)
    urgent_ingredients: list[str] = Field(default_factory=list)
